baseURL = "https://dino.codes/"
languageCode = "en-us"
title = "dino (dot) codes"
theme = "ink"

# Enable syntax highlighting.
pygmentsstyle = "monokailight"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-144751197-1"

[params]
  subtitle = "Thoughts and opinions on Software Development and Music Production."
  favicon = "static/favicon.ico"
  # Custom CSS added to default styles. Files added to `static` folder is copied as it is to
  # root by Hugo. For example if you have custom CSS file under `static/css/custom.css` then
  # you can specify custom css path as `css/custom.css`.
  customCSS = "css/custom.css"
  # # Custom CSS added to dark mode style.
  # customDarkCSS = "css/custom-dark.css"

  # Custom list of Javascript files to load. Just like custom CSS you can place js files under
  # `static/js` folder and specify path here as `js/script-name.js`. You can also specify full url,
  # for example you may want to include external JS library.
  # customJS = ["js/abc.js", "js/xyz.js", "https://code.jquery.com/jquery-3.4.1.js"] featherIconsCDN = true

  # Image to be displayed in Twitter Card.
  images = ["favicon.ico"]

# Links just below the website's title.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

# Social links to the right of the website title.
[[params.social]]
name = "Soundcloud"
icon = "music"
url = "https://soundcloud.com/dino-costa-180136083"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/joaofcosta_"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/joaofcosta/"

# [[params.social]]
# name = "Medium"
# icon = "book"
# url = "https://medium.com/@dinojoaocosta"

# Enable tags.
[taxonomies]
   tag = "tags"
