baseURL = "http://www.dino.codes/"
languageCode = "en-us"
title = "dino (dot) codes"
theme = "hyde"
pygmentsCodeFences = true
pygmentsStyle = "monokailight"
googleAnalytics = "UA-144751197-1"

[pygmentsOptions]
linenos = true

[params]
description = "Thoughts and opinions on Software Development and Music Production."

[[menu.main]]
name = "Github"
url = "https://github.com/joaofcosta/"

[[menu.main]]
name = "Twitter"
url = "https://twitter.com/joaofcosta_"

[[menu.main]]
name = "Medium"
url = "https://medium.com/@dinojoaocosta"
